system_mode: CHAOS
default_tags:
  - "[SYSTEM]: CHAOS"
  - "[STABILITY]: LOW"
  - "[TREMOR]: GLOBAL"

symbolic_paths:
  threads:
    - "~/EdenOS_Origin"
    - "~/Eden_Rebuild"
  sacred: []
  tender:
    - "~/EdenOS_Origin"
    - "~/Eden_Rebuild"
  unstable: []
  ignored:
    - "${SYSTEMROOT}"
    - "${PROGRAMFILES}"
    - "**/__pycache__/**"
    - "**/*.log"
    - "**/node_modules/**"
    - "**/.git/**"
